# Generated by Django 3.0.4 on 2020-03-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Higgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField()),
                ('class_label', models.FloatField()),
                ('jet_1_btag', models.FloatField()),
                ('jet_1_eta', models.FloatField()),
                ('jet_1_phi', models.FloatField()),
                ('jet_1_pt', models.FloatField()),
                ('jet_2_btag', models.FloatField()),
                ('jet_2_eta', models.FloatField()),
                ('jet_2_phi', models.FloatField()),
                ('jet_2_pt', models.FloatField()),
                ('jet_3_btag', models.FloatField()),
                ('jet_3_eta', models.FloatField()),
                ('jet_3_phi', models.FloatField()),
                ('jet_3_pt', models.FloatField()),
                ('jet_4_btag', models.FloatField()),
                ('jet_4_eta', models.FloatField()),
                ('jet_4_phi', models.FloatField()),
                ('jet_4_pt', models.FloatField()),
                ('lepton_eta', models.FloatField()),
                ('lepton_pt', models.FloatField()),
                ('lepton_phi', models.FloatField()),
                ('m_bb', models.FloatField()),
                ('m_jj', models.FloatField()),
                ('m_jjj', models.FloatField()),
                ('m_jlv', models.FloatField()),
                ('m_lv', models.FloatField()),
                ('m_wbb', models.FloatField()),
                ('m_wwbb', models.FloatField()),
                ('missing_energy_magnitude', models.FloatField()),
                ('missing_energy_phi', models.FloatField()),
            ],
        ),
    ]
