# Generated by Django 3.0.4 on 2020-03-08 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='higgs',
            name='key',
        ),
    ]
